### ISSUE TITLE
Have you considered adding a license to the code?

### ISSUE THREAD

**Issue by ColdSauce** [riolet/ritchie#37]
To preface, I'm not a lawyer so don't take any of this as legal advice but this repo doesn't have a license. This means that it technically isn't an open source project.

So, I highly recommend, if you want to get people to contribute, to add a license. This could be as simple as a license file on the repo.

Here's a bunch of websites where you could read more about FOSS licenses and what they mean:

https://tldrlegal.com/
http://choosealicense.com/

This article is a bit preachy and gives off a bad tone which I don't like but it's the best one I've found to explain why not having a license on your code hosted on Github is a bad thing.

http://readwrite.com/2013/05/15/open-source-is-old-school-says-the-github-generation

**Comment by rrezel** [comment]
Thank you, sir!
Here's the licence:

The source code is distributed under the GNU General Public License version 3, with the addition under section 7 of an exception described in the “Ritchie Runtime Library Exception, version 3.1” (Please see Ritchie RUNTIME LIBRARY EXCEPTION)

https://github.com/riolet/ritchie/blob/master/LICENCE.md

**Comment by Calinou** [comment]
Some issues remain though:

- You should add some licensing headers at the top of each source code file.
- You should allow later versions of the GPL to be used (through the "or at your option, any later version" mechanism)
